### ISSUE TITLE
Inbox crashes in 5.14.3 version

### ISSUE THREAD

**Issue by crilly** [Pushwoosh/pushwoosh-inbox-ui-android-sdk#4]
Hi all, 
I need to update PushWoosh version to 5.14.3 in order to resolve Zip Path Traversal Vulnerability problem, but the Inbox crashes at opening with this error:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/PushwooshPlatform;`
 `       at com.pushwoosh.inbox.d.a.<init>(Unknown Source:21)`
  `      at com.pushwoosh.inbox.internal.b.a(Unknown Source:27)`
   `     at com.pushwoosh.inbox.PushwooshInbox.loadMessages(Unknown Source:0)`
 `       at com.pushwoosh.inbox.ui.model.repository.InboxRepository.loadInbox(InboxRepository.kt:82)`
`        at com.pushwoosh.inbox.ui.presentation.presenter.InboxPresenter.onCreate(InboxPresenter.kt:69)`
       ` at com.pushwoosh.inbox.ui.presentation.view.fragment.BaseFragment.onCreate(BaseFragment.kt:48)`
        `at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)`
       ` at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)`
        `at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)`
       ` at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)`
       ` at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)`
       ` at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)`
        `at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)`
       ` at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)`
       ` at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)`
       ` at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)`
        `at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)`
        `at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)`
      `  at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)`
      `  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)`
      `  at android.app.Activity.performStart(Activity.java:7157)`
       ` at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2949)`
       ` at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)`
      `  at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)`
      `  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)`
        `at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)`
       ` at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)`
       ` at android.os.Handler.dispatchMessage(Handler.java:106)`
      `  at android.os.Looper.loop(Looper.java:193)`
      `  at android.app.ActivityThread.main(ActivityThread.java:6762)`
       ` at java.lang.reflect.Method.invoke(Native Method)`
      `  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)`
      `  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`
     `Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.PushwooshPlatform" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.my.app-LAxwlv90GLcs5_cf1e8H9Q==/base.apk", zip file "/data/app/com.my.app-LAxwlv90GLcs5_cf1e8H9Q==/split_lib_resources_apk.apk", zip file "/data/app/com.my.app-LAxwlv90GLcs5_cf1e8H9Q==/split_lib_slice_0_apk.apk"],nativeLibraryDirectories=[/data/app/com.my.app-LAxwlv90GLcs5_cf1e8H9Q==/lib/arm64, /data/app/com.my.app-LAxwlv90GLcs5_cf1e8H9Q==/base.apk!/lib/arm64-v8a, /data/app/com.my.app-LAxwlv90GLcs5_cf1e8H9Q==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.my.app-LAxwlv90GLcs5_cf1e8H9Q==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]`
       ` at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)`
     `   at java.lang.ClassLoader.loadClass(ClassLoader.java:379)`
     `   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`
    `    at com.pushwoosh.inbox.d.a.<init>(Unknown Source:21) `
    `    at com.pushwoosh.inbox.internal.b.a(Unknown Source:27) `
    `    at com.pushwoosh.inbox.PushwooshInbox.loadMessages(Unknown Source:0) `
    `    at com.pushwoosh.inbox.ui.model.repository.InboxRepository.loadInbox(InboxRepository.kt:82) `
     `   at com.pushwoosh.inbox.ui.presentation.presenter.InboxPresenter.onCreate(InboxPresenter.kt:69) `
      `  at com.pushwoosh.inbox.ui.presentation.view.fragment.BaseFragment.onCreate(BaseFragment.kt:48) `
      `  at android.support.v4.app.Fragment.performCreate(Fragment.java:2331) `
      `  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386) `
       ` at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188) `
      `  at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)` 
       ` at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115) `
      `  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380) `
      `  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) `
      `  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) `
      `  at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248) `
      `  at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)` 
       ` at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195) `
    `    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597) `
    `    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177) `
       ` at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392) `
      `  at android.app.Activity.performStart(Activity.java:7157) `
      `  at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2949) `
    `    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) `
   `     at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) `
       ` at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) `
     `   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) `
     `   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818) `
      `  at android.os.Handler.dispatchMessage(Handler.java:106) `
     `   at android.os.Looper.loop(Looper.java:193) `
      `  at android.app.ActivityThread.main(ActivityThread.java:6762) `
      `  at java.lang.reflect.Method.invoke(Native Method) `
      `  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) `
     `   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `
`Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.my.app-LAxwlv90GLcs5_cf1e8H9Q==/split_lib_resources_apk.apk`
       ` at dalvik.system.DexFile.openDexFileNative(Native Method)`
      `  at dalvik.system.DexFile.openDexFile(DexFile.java:354)`
       ` at dalvik.system.DexFile.<init>(DexFile.java:101)`
      `  at dalvik.system.DexFile.<init>(DexFile.java:75)`
      `  at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)`
      `  at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)`
       ` at dalvik.system.DexPathList.<init>(DexPathList.java:164)`
      `  at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)`
      `  at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)`
      `  at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)`
    `    at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)`
       ` at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)`
      `  at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)`
       ` at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)`
      `  at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:718)`
      `  at android.app.LoadedApk.getClassLoader(LoadedApk.java:801)`
      `  at android.app.LoadedApk.getResources(LoadedApk.java:1023)`
    `    at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)`
     `   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5780)`
     `   at android.app.ActivityThread.access$1100(ActivityThread.java:200)`
      `  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)`
        	`	... 6 more`

Thank you for support

**Comment by wfhm** [comment]
Hi @crilly,

Checking it

**Comment by wfhm** [comment]
@crilly

Just fixed this issue in the latest release of our SDK. Please update it in your app
